title: Tokyo Debunker Info Summaries
description: > # this means to ignore newlines until "baseurl:"
  Tokyo Debunker information summaries for use with fan created AI bot projects.
permalink: ':title/'
baseurl: "/tdb-lore" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Darkwick Debunker # add your name
author-img: david-freeman.jpg # add your photo
about-author: Information summaries for Tokyo Debunker. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: izzyfisher # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: darkwickdebunker@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
